# Use Python base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy app files
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

# Expose port your Flask app runs on
EXPOSE 5000

# Start the app
CMD ["python", "app.py"]
